# 仅用于「引用资源」合并到现有配置，不能用于「下载配置」
# 引用 URL（粘贴到：长按配置 → 引用资源）：
# https://raw.githubusercontent.com/3913305-dev/sectoggle/main/TPlayerFakeVIP/QuantumultX/tplayer_fakevip.resource.conf

[mitm]
hostname = teslaapi.twanjia.com, *.twanjia.com

[rewrite_remote]
https://raw.githubusercontent.com/3913305-dev/sectoggle/main/TPlayerFakeVIP/QuantumultX/tplayer_fakevip.rewrite, tag=TPlayer-FakeVIP, update-interval=86400, opt-parser=true, enabled=true

[script]
https://raw.githubusercontent.com/3913305-dev/sectoggle/main/TPlayerFakeVIP/QuantumultX/tplayer_fakevip.js, tag=tplayer_fakevip.js, enabled=true
